### ISSUE TITLE
Elite bosses :(

### ISSUE THREAD

**Issue by nehcap** [trankevint/maple-bot#15]
what i can do about them?

**Comment by qlvbrknp** [comment]
Hi nehcap,

I won't be updating this program so I will not be able to provide any code. However, I can provide some suggestions with how I would implement elite boss detection. 

When elite bosses are about to appear, the screen fades to black, a warning message pops up, a timer appears in the top middle of your screen, and a HP bar at the top of the screen. The screen fading to black and warning message are brief, you would not be able to reliably check for them unless you are constantly checking for them. This can also pose issues in regards to efficiency and performance as it will require more resources to maintain. However, the timer and HP bar will stay for as long as the elite boss is in the map, making them much more reliable sources of truth. Therefore, we can...

1. Check for "red" pixels near the top of the screen at an interval of X units of time (to detect HP bar).
2. Check for "black" pixels near the top of the screen at an interval of X units of time (to detect timer).
3. Use template matching functionality from OpenCV at an interval of X units of time (either HP bar or timer).

Best of luck to you!
