### ISSUE TITLE
MapleStory resolution

### ISSUE THREAD

**Issue by GHHTKN** [trankevint/maple-bot#19]
Hi,The content of rune_solver.py says that the resolution of MapleStory is 800x600. Can I change it to 1024x768?

Thanks

**Comment by qlvbrknp** [comment]
Hello GHHTKN,

The current code is set to only search within the area that the rune captcha will appear in on 800x600 resolution but this will change for 1024x768 resolution, so you will have to edit the values in lines 113 and 114 of `rune_solver.py`.
